import type {
  BusinessDto,
  CategoryDto,
  ReviewDto,
  VaultReceiptDto,
} from "./types";

/**
 * Seed data in **wire shape** — exactly what the API in the backend spec would
 * return. Amounts are integer paise (§7), keys are snake_case, tiers and
 * statuses use the spec's vocabularies.
 *
 * The mock transport serves these. When `NEXT_PUBLIC_API_BASE_URL` is set this
 * file stops being read at all, and nothing else has to change.
 */

/** ₹ → paise. Keeps the seed readable while the wire stays integer. */
const p = (rupees: number) => rupees * 100;

/* -------------------------------------------------------------------------- */
/* Categories — GET /categories                                                */
/* -------------------------------------------------------------------------- */

export const CATEGORY_DTOS: CategoryDto[] = [
  {
    id: "cat_hospitals",
    slug: "hospitals",
    name: "Hospital",
    plural: "Hospitals",
    blurb:
      "Multispecialty and single-specialty hospitals, rated on the bill you actually paid.",
    parent_id: null,
    icon: null,
    is_active: true,
    sort_order: 1,
    aspects: [
      { key: "doctor_quality", label: "Doctor quality", sort_order: 1, weight: 1 },
      { key: "staff_behaviour", label: "Staff behaviour", sort_order: 2, weight: 1 },
      { key: "cleanliness", label: "Cleanliness", sort_order: 3, weight: 1 },
      {
        key: "billing_transparency",
        label: "Billing clarity",
        sort_order: 4,
        weight: 1,
      },
      { key: "wait_time", label: "Wait time", sort_order: 5, weight: 1 },
    ],
    fields: [
      // Three levels, one field: the picker writes `treatment_category`,
      // `treatment_speciality` and `treatment_procedure` into `structured`.
      // A department select alongside it would ask the same question twice.
      {
        key: "treatment",
        label: "Treatment",
        type: "treatment",
        options: null,
        required: false,
      },
      {
        key: "total_cost",
        label: "Total cost",
        type: "currency",
        options: null,
        required: false,
      },
      {
        key: "days_admitted",
        label: "Days admitted",
        type: "number",
        options: null,
        required: false,
      },
      {
        key: "insurance_used",
        label: "Insurance used",
        type: "boolean",
        options: null,
        required: false,
      },
    ],
    receipt: {
      expects: "a discharge summary or a hospital bill",
      amount_tolerance: 0.1,
    },
  },
  {
    id: "cat_clinics",
    slug: "clinics",
    name: "Clinic",
    plural: "Clinics",
    blurb: "Day clinics and consulting rooms, verified against the OPD receipt.",
    parent_id: null,
    icon: null,
    is_active: true,
    sort_order: 2,
    aspects: [
      { key: "doctor_quality", label: "Doctor quality", sort_order: 1, weight: 1 },
      { key: "staff_behaviour", label: "Staff behaviour", sort_order: 2, weight: 1 },
      { key: "cleanliness", label: "Cleanliness", sort_order: 3, weight: 1 },
      {
        key: "billing_transparency",
        label: "Billing clarity",
        sort_order: 4,
        weight: 1,
      },
      { key: "wait_time", label: "Wait time", sort_order: 5, weight: 1 },
    ],
    fields: [
      {
        key: "treatment",
        label: "Reason for visit",
        type: "treatment",
        options: null,
        required: false,
      },
      {
        key: "total_cost",
        label: "Consultation fee",
        type: "currency",
        options: null,
        required: false,
      },
      {
        key: "insurance_used",
        label: "Insurance used",
        type: "boolean",
        options: null,
        required: false,
      },
    ],
    receipt: {
      expects: "an OPD or consultation receipt",
      amount_tolerance: 0.05,
    },
  },
  {
    id: "cat_labs",
    slug: "labs",
    name: "Diagnostics lab",
    plural: "Diagnostics labs",
    blurb:
      "Pathology and imaging centres, rated on turnaround and real pricing.",
    parent_id: null,
    icon: null,
    is_active: true,
    sort_order: 3,
    aspects: [
      { key: "accuracy", label: "Report accuracy", sort_order: 1, weight: 1 },
      { key: "turnaround", label: "Turnaround time", sort_order: 2, weight: 1 },
      { key: "staff_behaviour", label: "Staff behaviour", sort_order: 3, weight: 1 },
      { key: "cleanliness", label: "Cleanliness", sort_order: 4, weight: 1 },
      {
        key: "billing_transparency",
        label: "Billing clarity",
        sort_order: 5,
        weight: 1,
      },
    ],
    fields: [
      { key: "test_type", label: "Test", type: "text", options: null, required: false },
      {
        key: "total_cost",
        label: "Amount paid",
        type: "currency",
        options: null,
        required: false,
      },
      {
        key: "report_hours",
        label: "Report in (hours)",
        type: "number",
        options: null,
        required: false,
      },
      {
        key: "home_collection",
        label: "Home collection",
        type: "boolean",
        options: null,
        required: false,
      },
    ],
    receipt: { expects: "a lab invoice", amount_tolerance: 0.05 },
  },
  {
    id: "cat_dentists",
    slug: "dentists",
    name: "Dentist",
    plural: "Dentists",
    blurb: "Dental clinics, where quoted price and final bill rarely match.",
    parent_id: null,
    icon: null,
    is_active: true,
    sort_order: 4,
    aspects: [
      { key: "doctor_quality", label: "Dentist skill", sort_order: 1, weight: 1 },
      { key: "pain_management", label: "Pain management", sort_order: 2, weight: 1 },
      { key: "cleanliness", label: "Cleanliness", sort_order: 3, weight: 1 },
      {
        key: "billing_transparency",
        label: "Billing clarity",
        sort_order: 4,
        weight: 1,
      },
      { key: "wait_time", label: "Wait time", sort_order: 5, weight: 1 },
    ],
    fields: [
      {
        key: "treatment",
        label: "Treatment",
        type: "treatment",
        options: null,
        required: false,
      },
      {
        key: "total_cost",
        label: "Total cost",
        type: "currency",
        options: null,
        required: false,
      },
      {
        key: "sittings",
        label: "Sittings",
        type: "number",
        options: null,
        required: false,
      },
      {
        key: "quote_matched",
        label: "Final bill matched quote",
        type: "boolean",
        options: null,
        required: false,
      },
    ],
    receipt: { expects: "a treatment bill", amount_tolerance: 0.05 },
  },
];

/* -------------------------------------------------------------------------- */
/* Businesses — GET /businesses/:idOrSlug                                      */
/* -------------------------------------------------------------------------- */

export const BUSINESS_DTOS: BusinessDto[] = [
  {
    id: "01J8RUBY",
    slug: "ruby-hall-clinic-pune",
    name: "Ruby Hall Clinic",
    category: { id: "cat_hospitals", slug: "hospitals", name: "Hospital" },
    address: {
      line1: "40 Sassoon Road, Sangamvadi",
      area: "Sassoon Road",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411001",
    },
    geo: { lat: 18.5314, lng: 73.877 },
    phone: "+91 20 6645 5000",
    hours: "Open 24 hours",
    descriptor: "Multispecialty",
    specialities: ["Cardiology", "Orthopaedics", "Oncology", "Emergency"],
    status: "claimed",
    ratings: {
      verified: { score: 4.2, count: 318, distribution: [6, 14, 41, 120, 137] },
      unverified: { score: 3.6, count: 891 },
    },
    aspects: [
      { key: "doctor_quality", label: "Doctor quality", score: 4.5 },
      { key: "cleanliness", label: "Cleanliness", score: 4.4 },
      { key: "staff_behaviour", label: "Staff behaviour", score: 3.7 },
      { key: "wait_time", label: "Wait time", score: 3.2 },
      { key: "billing_transparency", label: "Billing clarity", score: 2.9 },
    ],
    cost: {
      band: 3,
      currency: "INR",
      p25: p(18_000),
      p50: p(47_500),
      p75: p(96_000),
      based_on_receipts: 318,
    },
    can_review: true,
    photos: [{ id: "m1", url: null, seed: 11 }],
  },
  {
    id: "01J8SAHY",
    slug: "sahyadri-hospital-deccan",
    name: "Sahyadri Hospital",
    category: { id: "cat_hospitals", slug: "hospitals", name: "Hospital" },
    address: {
      line1: "Plot 30-C, Erandwane, Karve Road",
      area: "Deccan Gymkhana",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411004",
    },
    geo: { lat: 18.5089, lng: 73.8351 },
    phone: "+91 20 6721 3000",
    hours: "Open 24 hours",
    descriptor: "Multispecialty",
    specialities: ["Neurology", "Nephrology", "Maternity"],
    status: "claimed",
    ratings: {
      verified: { score: 3.8, count: 142, distribution: [9, 15, 32, 48, 38] },
      unverified: { score: 4.1, count: 604 },
    },
    aspects: [
      { key: "doctor_quality", label: "Doctor quality", score: 4.3 },
      { key: "cleanliness", label: "Cleanliness", score: 4.0 },
      { key: "staff_behaviour", label: "Staff behaviour", score: 3.6 },
      { key: "billing_transparency", label: "Billing clarity", score: 3.4 },
      { key: "wait_time", label: "Wait time", score: 3.0 },
    ],
    cost: {
      band: 3,
      currency: "INR",
      p25: p(12_000),
      p50: p(52_000),
      p75: p(1_28_000),
      based_on_receipts: 142,
    },
    can_review: true,
    solicits_reviews: true,
    photos: [{ id: "m2", url: null, seed: 24 }],
  },
  {
    id: "01J8JEHA",
    slug: "jehangir-hospital-pune",
    name: "Jehangir Hospital",
    category: { id: "cat_hospitals", slug: "hospitals", name: "Hospital" },
    address: {
      line1: "32 Sassoon Road, Agarkar Nagar",
      area: "Sassoon Road",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411001",
    },
    geo: { lat: 18.5286, lng: 73.8767 },
    phone: "+91 20 6681 9999",
    hours: "Open 24 hours",
    descriptor: "Multispecialty",
    specialities: ["Cardiology", "Gastroenterology", "Paediatrics"],
    status: "unclaimed",
    ratings: {
      verified: { score: 4.0, count: 207, distribution: [8, 12, 38, 76, 73] },
      unverified: { score: 3.4, count: 512 },
    },
    aspects: [
      { key: "doctor_quality", label: "Doctor quality", score: 4.4 },
      { key: "cleanliness", label: "Cleanliness", score: 4.2 },
      { key: "staff_behaviour", label: "Staff behaviour", score: 3.9 },
      { key: "wait_time", label: "Wait time", score: 3.5 },
      { key: "billing_transparency", label: "Billing clarity", score: 3.1 },
    ],
    cost: {
      band: 3,
      currency: "INR",
      p25: p(16_500),
      p50: p(44_000),
      p75: p(1_08_000),
      based_on_receipts: 207,
    },
    can_review: true,
    photos: [{ id: "m3", url: null, seed: 37 }],
  },
  {
    id: "01J8DEEN",
    slug: "deenanath-mangeshkar-hospital",
    name: "Deenanath Mangeshkar Hospital",
    category: { id: "cat_hospitals", slug: "hospitals", name: "Hospital" },
    address: {
      line1: "Near Mhatre Bridge, Erandwane",
      area: "Erandwane",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411004",
    },
    geo: { lat: 18.5074, lng: 73.8285 },
    phone: "+91 20 4015 1000",
    hours: "Open 24 hours",
    descriptor: "Multispecialty · Charitable trust",
    specialities: ["Oncology", "Cardiology", "Maternity", "Emergency"],
    status: "claimed",
    ratings: {
      verified: { score: 4.4, count: 389, distribution: [7, 11, 40, 128, 203] },
      unverified: { score: 4.0, count: 1_120 },
    },
    aspects: [
      { key: "doctor_quality", label: "Doctor quality", score: 4.6 },
      { key: "billing_transparency", label: "Billing clarity", score: 4.3 },
      { key: "cleanliness", label: "Cleanliness", score: 4.3 },
      { key: "staff_behaviour", label: "Staff behaviour", score: 4.1 },
      { key: "wait_time", label: "Wait time", score: 2.8 },
    ],
    cost: {
      band: 2,
      currency: "INR",
      p25: p(9_000),
      p50: p(31_000),
      p75: p(78_000),
      based_on_receipts: 389,
    },
    can_review: true,
    photos: [{ id: "m4", url: null, seed: 42 }],
  },
  {
    id: "01J8KEMH",
    slug: "kem-hospital-pune",
    name: "KEM Hospital",
    category: { id: "cat_hospitals", slug: "hospitals", name: "Hospital" },
    address: {
      line1: "489 Rasta Peth, Sardar Moodliar Road",
      area: "Rasta Peth",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411011",
    },
    geo: { lat: 18.5245, lng: 73.8724 },
    phone: "+91 20 6603 7300",
    hours: "Open 24 hours",
    descriptor: "General · Research",
    specialities: ["Maternity", "General medicine", "Diabetology"],
    status: "unclaimed",
    ratings: {
      verified: { score: 3.9, count: 96, distribution: [5, 8, 20, 33, 30] },
      unverified: { score: 3.2, count: 288 },
    },
    aspects: [
      { key: "doctor_quality", label: "Doctor quality", score: 4.2 },
      { key: "billing_transparency", label: "Billing clarity", score: 4.0 },
      { key: "staff_behaviour", label: "Staff behaviour", score: 3.8 },
      { key: "cleanliness", label: "Cleanliness", score: 3.6 },
      { key: "wait_time", label: "Wait time", score: 2.6 },
    ],
    cost: {
      band: 2,
      currency: "INR",
      p25: p(4_500),
      p50: p(14_800),
      p75: p(42_000),
      based_on_receipts: 96,
    },
    can_review: true,
    photos: [{ id: "m5", url: null, seed: 58 }],
  },
  {
    id: "01J8ADIT",
    slug: "aditya-birla-memorial-hospital",
    name: "Aditya Birla Memorial Hospital",
    category: { id: "cat_hospitals", slug: "hospitals", name: "Hospital" },
    address: {
      line1: "Aditya Birla Marg, Thergaon, Chinchwad",
      area: "Chinchwad",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411033",
    },
    geo: { lat: 18.6186, lng: 73.7716 },
    phone: "+91 20 3071 7500",
    hours: "Open 24 hours",
    descriptor: "Multispecialty",
    specialities: ["Orthopaedics", "Cardiology", "Neurology"],
    status: "claimed",
    ratings: {
      verified: { score: 3.5, count: 74, distribution: [8, 10, 19, 22, 15] },
      unverified: { score: 3.9, count: 431 },
    },
    aspects: [
      { key: "cleanliness", label: "Cleanliness", score: 4.1 },
      { key: "doctor_quality", label: "Doctor quality", score: 3.9 },
      { key: "staff_behaviour", label: "Staff behaviour", score: 3.3 },
      { key: "wait_time", label: "Wait time", score: 3.1 },
      { key: "billing_transparency", label: "Billing clarity", score: 2.4 },
    ],
    cost: {
      band: 4,
      currency: "INR",
      p25: p(22_000),
      p50: p(68_000),
      p75: p(1_62_000),
      based_on_receipts: 74,
    },
    can_review: true,
    photos: [{ id: "m6", url: null, seed: 63 }],
  },
  {
    id: "01J8SHAH",
    slug: "dr-shah-skin-clinic-kothrud",
    name: "Dr. Shah Skin & Laser Clinic",
    category: { id: "cat_clinics", slug: "clinics", name: "Clinic" },
    address: {
      line1: "1st Floor, Paud Road, Kothrud",
      area: "Kothrud",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411038",
    },
    geo: { lat: 18.5074, lng: 73.8077 },
    phone: "+91 20 2546 1120",
    hours: "10:00 – 20:00 · Closed Sunday",
    descriptor: "Dermatology",
    specialities: ["Dermatology"],
    status: "claimed",
    ratings: {
      verified: { score: 4.6, count: 88, distribution: [1, 2, 6, 22, 57] },
      unverified: { score: 4.2, count: 143 },
    },
    aspects: [
      { key: "doctor_quality", label: "Doctor quality", score: 4.8 },
      { key: "cleanliness", label: "Cleanliness", score: 4.7 },
      { key: "billing_transparency", label: "Billing clarity", score: 4.5 },
      { key: "staff_behaviour", label: "Staff behaviour", score: 4.4 },
      { key: "wait_time", label: "Wait time", score: 4.0 },
    ],
    cost: {
      band: 2,
      currency: "INR",
      p25: p(600),
      p50: p(1_400),
      p75: p(4_800),
      based_on_receipts: 88,
    },
    can_review: true,
    photos: [{ id: "m7", url: null, seed: 71 }],
  },
  {
    id: "01J8APEX",
    slug: "apex-family-clinic-baner",
    name: "Apex Family Clinic",
    category: { id: "cat_clinics", slug: "clinics", name: "Clinic" },
    address: {
      line1: "Shop 4, Baner Road, Baner",
      area: "Baner",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411045",
    },
    geo: { lat: 18.5642, lng: 73.7769 },
    phone: "+91 20 2729 4411",
    hours: "09:00 – 21:00",
    descriptor: "General practice",
    specialities: ["General practice", "Physiotherapy"],
    status: "unclaimed",
    // Under the five-verified-review threshold in §6 — the profile must say
    // "not enough verified reviews yet" rather than publish a headline score.
    ratings: {
      verified: { score: 3.6, count: 3, distribution: [0, 1, 0, 1, 1] },
      unverified: { score: 3.8, count: 97 },
    },
    aspects: [
      { key: "wait_time", label: "Wait time", score: 4.2 },
      { key: "staff_behaviour", label: "Staff behaviour", score: 3.8 },
      { key: "doctor_quality", label: "Doctor quality", score: 3.5 },
      { key: "cleanliness", label: "Cleanliness", score: 3.4 },
      { key: "billing_transparency", label: "Billing clarity", score: 3.1 },
    ],
    cost: {
      band: 1,
      currency: "INR",
      p25: p(400),
      p50: p(750),
      p75: p(1_900),
      based_on_receipts: 3,
    },
    can_review: true,
    photos: [{ id: "m8", url: null, seed: 84 }],
  },
  {
    id: "01J8METR",
    slug: "metropolis-labs-shivajinagar",
    name: "Metropolis Diagnostics",
    category: { id: "cat_labs", slug: "labs", name: "Diagnostics lab" },
    address: {
      line1: "Ground Floor, JM Road, Shivajinagar",
      area: "Shivajinagar",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411005",
    },
    geo: { lat: 18.5286, lng: 73.8478 },
    phone: "+91 20 3399 2020",
    hours: "07:00 – 21:00",
    descriptor: "Pathology · Imaging",
    specialities: ["Pathology", "Radiology"],
    status: "claimed",
    ratings: {
      verified: { score: 4.1, count: 156, distribution: [5, 9, 27, 62, 53] },
      unverified: { score: 3.5, count: 210 },
    },
    aspects: [
      { key: "accuracy", label: "Report accuracy", score: 4.5 },
      { key: "turnaround", label: "Turnaround time", score: 4.3 },
      { key: "cleanliness", label: "Cleanliness", score: 4.1 },
      { key: "staff_behaviour", label: "Staff behaviour", score: 3.9 },
      { key: "billing_transparency", label: "Billing clarity", score: 3.6 },
    ],
    cost: {
      band: 2,
      currency: "INR",
      p25: p(350),
      p50: p(1_850),
      p75: p(5_400),
      based_on_receipts: 156,
    },
    can_review: true,
    photos: [{ id: "m9", url: null, seed: 92 }],
  },
  {
    id: "01J8THYR",
    slug: "thyrocare-collection-centre-viman-nagar",
    name: "Thyrocare Collection Centre",
    category: { id: "cat_labs", slug: "labs", name: "Diagnostics lab" },
    address: {
      line1: "Nagar Road, Viman Nagar",
      area: "Viman Nagar",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411014",
    },
    geo: { lat: 18.5679, lng: 73.9143 },
    phone: "+91 20 6720 1188",
    hours: "06:30 – 19:00",
    descriptor: "Pathology",
    specialities: ["Pathology"],
    status: "unclaimed",
    ratings: {
      verified: { score: 3.4, count: 63, distribution: [7, 9, 18, 17, 12] },
      unverified: { score: 3.7, count: 122 },
    },
    aspects: [
      { key: "billing_transparency", label: "Billing clarity", score: 4.2 },
      { key: "turnaround", label: "Turnaround time", score: 3.6 },
      { key: "accuracy", label: "Report accuracy", score: 3.4 },
      { key: "cleanliness", label: "Cleanliness", score: 3.2 },
      { key: "staff_behaviour", label: "Staff behaviour", score: 2.9 },
    ],
    cost: {
      band: 2,
      currency: "INR",
      p25: p(250),
      p50: p(990),
      p75: p(2_600),
      based_on_receipts: 63,
    },
    can_review: true,
    photos: [{ id: "m10", url: null, seed: 103 }],
  },
  {
    id: "01J8SMIL",
    slug: "smilecare-dental-aundh",
    name: "SmileCare Dental Studio",
    category: { id: "cat_dentists", slug: "dentists", name: "Dentist" },
    address: {
      line1: "Above Bank, ITI Road, Aundh",
      area: "Aundh",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411007",
    },
    geo: { lat: 18.5593, lng: 73.8078 },
    phone: "+91 20 2588 7766",
    hours: "10:00 – 20:30 · Closed Tuesday",
    descriptor: "Dental",
    specialities: ["Implants", "Orthodontics"],
    status: "claimed",
    ratings: {
      verified: { score: 4.3, count: 71, distribution: [2, 3, 8, 26, 32] },
      unverified: { score: 4.6, count: 188 },
    },
    aspects: [
      { key: "doctor_quality", label: "Dentist skill", score: 4.6 },
      { key: "pain_management", label: "Pain management", score: 4.4 },
      { key: "cleanliness", label: "Cleanliness", score: 4.4 },
      { key: "wait_time", label: "Wait time", score: 4.1 },
      { key: "billing_transparency", label: "Billing clarity", score: 3.7 },
    ],
    cost: {
      band: 3,
      currency: "INR",
      p25: p(800),
      p50: p(6_200),
      p75: p(38_000),
      based_on_receipts: 71,
    },
    can_review: true,
    solicits_reviews: true,
    photos: [{ id: "m11", url: null, seed: 118 }],
  },
];

/* -------------------------------------------------------------------------- */
/* Reviews — GET /businesses/:id/reviews                                       */
/* -------------------------------------------------------------------------- */

export const REVIEW_DTOS: ReviewDto[] = [
  {
    id: "01JB1001",
    business_id: "01J8RUBY",
    business_slug: "ruby-hall-clinic-pune",
    author: {
      id: "u_rhea",
      display_name: "Rhea M.",
      trust_level: 4,
      verified_review_count: 11,
    },
    rating: 3,
    title: "Surgery was excellent, discharge was not",
    body: "Angioplasty went smoothly and Dr. Kulkarni explained every step before and after. The problem was afterwards — discharge took six hours because the billing desk and the insurance desk were sending us between each other. Nobody could tell us what the final number would be until the very end, and the estimate we were given at admission was short by about ₹9,000 in consumables that were never itemised for us. Clinically I would come back. Administratively, budget an extra half-day.",
    language: "en",
    aspect_ratings: {
      doctor_quality: 5,
      staff_behaviour: 3,
      cleanliness: 4,
      billing_transparency: 2,
      wait_time: 1,
    },
    structured: {
      treatment_category: "Surgical Treatment",
      treatment_speciality: "Cardiology",
      treatment_procedure: "Angioplasty",
      days_admitted: 3,
      insurance_used: true,
    },
    verification_tier: "verified",
    weight: 1,
    is_anonymous: false,
    status: "published",
    helpful_count: 42,
    report_count: 0,
    visit_date: "2026-03-14",
    bill_amount: p(42_300),
    published_at: "2026-03-18",
    edited_at: null,
    reply: {
      id: "rep_1",
      business_id: "01J8RUBY",
      author_display_name: "Ruby Hall Clinic",
      created_at: "2026-03-21",
      body: "Thank you for the detail, Rhea. The six-hour discharge is a known bottleneck when insurance pre-authorisation runs past 4pm and we are piloting a dedicated evening desk from April. On the consumables line — we have asked the billing team to hand over an itemised estimate at admission going forward.",
    },
  },
  {
    id: "01JB1002",
    business_id: "01J8RUBY",
    business_slug: "ruby-hall-clinic-pune",
    author: null,
    rating: 5,
    title: "Emergency at 2am, seen in eleven minutes",
    body: "Brought my father in with chest pain just after 2am. Triage was immediate, ECG within eleven minutes, and the cardiologist on call came down himself rather than sending a junior. The bill was close to the estimate. I am posting this anonymously but the bill is real.",
    language: "en",
    aspect_ratings: {
      doctor_quality: 5,
      staff_behaviour: 5,
      cleanliness: 5,
      billing_transparency: 4,
      wait_time: 4,
    },
    structured: {
      treatment_category: "Surgical Treatment",
      treatment_speciality: "Emergency Medicine",
      treatment_procedure: "Casulaty Management for Medical Illness",
      days_admitted: 5,
      insurance_used: true,
    },
    verification_tier: "verified",
    weight: 1,
    is_anonymous: true,
    status: "published",
    helpful_count: 88,
    report_count: 0,
    visit_date: "2026-05-02",
    bill_amount: p(1_18_600),
    published_at: "2026-05-04",
    edited_at: null,
    reply: null,
  },
  {
    id: "01JB1003",
    business_id: "01J8RUBY",
    business_slug: "ruby-hall-clinic-pune",
    author: {
      id: "u_sameer",
      display_name: "Sameer K.",
      trust_level: 3,
      verified_review_count: 6,
    },
    rating: 2,
    title: "Room charges changed twice mid-stay",
    body: "We were quoted a single-occupancy rate, moved to a different room on day two without being told the rate changed, and found out at checkout. The medical care was fine. The billing was not.",
    language: "en",
    aspect_ratings: {
      billing_transparency: 1,
      wait_time: 2,
      staff_behaviour: 2,
      doctor_quality: 4,
      cleanliness: 4,
    },
    structured: {
      treatment_category: "Surgical Treatment",
      treatment_speciality: "General Surgery",
      treatment_procedure: "Lap Cholecystectomy",
      days_admitted: 4,
      insurance_used: false,
    },
    verification_tier: "partial",
    weight: 0.5,
    is_anonymous: false,
    status: "under_review",
    helpful_count: 17,
    report_count: 0,
    visit_date: "2026-06-11",
    bill_amount: p(76_400),
    published_at: "2026-06-13",
    edited_at: null,
    reply: null,
    status_note:
      "The date on the bill is blurred — a moderator is checking it.",
  },
  {
    id: "01JB1004",
    business_id: "01J8RUBY",
    business_slug: "ruby-hall-clinic-pune",
    author: null,
    rating: 1,
    title: "Worst place ever",
    body: "Worst place ever, everyone there only wants money.",
    language: "en",
    aspect_ratings: {},
    structured: {},
    verification_tier: "unverified",
    weight: 0,
    is_anonymous: true,
    status: "published",
    helpful_count: 3,
    report_count: 2,
    visit_date: "2026-02-08",
    bill_amount: null,
    published_at: "2026-02-08",
    edited_at: null,
    reply: null,
  },
  {
    id: "01JB1005",
    business_id: "01J8RUBY",
    business_slug: "ruby-hall-clinic-pune",
    author: {
      id: "u_priya",
      display_name: "Priya D.",
      trust_level: 5,
      verified_review_count: 24,
    },
    rating: 1,
    title: "Charged for a scan that was never done",
    body: "There is a line item on our bill for an MRI that my mother never had. We have raised it with the billing desk twice.",
    language: "en",
    aspect_ratings: {
      staff_behaviour: 1,
      doctor_quality: 2,
      cleanliness: 3,
      billing_transparency: 1,
      wait_time: 1,
    },
    structured: {
      treatment_category: "Medical Management",
      treatment_speciality: "Medical Management Ward",
      treatment_procedure: "IV Fluids",
      days_admitted: 2,
      insurance_used: true,
    },
    verification_tier: "verified",
    weight: 0,
    is_anonymous: false,
    status: "disputed",
    helpful_count: 29,
    report_count: 1,
    visit_date: "2026-06-28",
    bill_amount: p(61_200),
    published_at: "2026-07-01",
    edited_at: null,
    reply: null,
    status_note:
      "Ruby Hall Clinic has disputed this review with evidence. It is frozen in the score until a moderator decides.",
  },
  {
    id: "01JB1006",
    business_id: "01J8DEEN",
    business_slug: "deenanath-mangeshkar-hospital",
    author: {
      id: "u_anjali",
      display_name: "Anjali P.",
      trust_level: 4,
      verified_review_count: 9,
    },
    rating: 5,
    title: "The estimate they gave was the bill I paid",
    body: "Delivery, three nights, and the final bill came within ₹1,200 of the written estimate handed to us at admission. That has never happened to me anywhere else. The wait in OPD before admission was long — nearly two hours — but I will take that trade any day.",
    language: "en",
    aspect_ratings: {
      billing_transparency: 5,
      doctor_quality: 5,
      cleanliness: 4,
      staff_behaviour: 4,
      wait_time: 2,
    },
    structured: {
      treatment_category: "Surgical Treatment",
      treatment_speciality: "Gynecology",
      treatment_procedure: "Normal Delivery",
      days_admitted: 3,
      insurance_used: true,
    },
    verification_tier: "verified",
    weight: 1,
    is_anonymous: false,
    status: "published",
    helpful_count: 134,
    report_count: 0,
    visit_date: "2026-04-19",
    bill_amount: p(68_900),
    published_at: "2026-04-22",
    edited_at: null,
    reply: null,
  },
  {
    id: "01JB1007",
    business_id: "01J8DEEN",
    business_slug: "deenanath-mangeshkar-hospital",
    author: null,
    rating: 4,
    title: "Six cycles of chemo, no surprise charges",
    body: "Oncology day-care ran on time on five of six visits. Costs were explained per cycle before we started, which made planning possible. Parking is the only real complaint.",
    language: "en",
    aspect_ratings: {
      doctor_quality: 5,
      billing_transparency: 4,
      staff_behaviour: 4,
      cleanliness: 4,
      wait_time: 3,
    },
    structured: {
      treatment_category: "Surgical Treatment",
      treatment_speciality: "Oncology",
      treatment_procedure: "Chemotherapy",
      days_admitted: 0,
      insurance_used: true,
    },
    verification_tier: "verified",
    weight: 1,
    is_anonymous: true,
    status: "published",
    helpful_count: 76,
    report_count: 0,
    visit_date: "2026-06-05",
    bill_amount: p(2_14_000),
    published_at: "2026-06-08",
    edited_at: null,
    reply: null,
  },
  {
    id: "01JB1008",
    business_id: "01J8SAHY",
    business_slug: "sahyadri-hospital-deccan",
    author: {
      id: "u_nikhil",
      display_name: "Nikhil R.",
      trust_level: 2,
      verified_review_count: 3,
    },
    rating: 4,
    title: "Neurology consult worth the wait",
    body: "Second opinion on my mother's tremor. The consultant spent forty minutes, went through two years of old reports, and did not order a single unnecessary scan. Reception is chaotic at peak hours.",
    language: "en",
    aspect_ratings: {
      doctor_quality: 5,
      cleanliness: 4,
      staff_behaviour: 4,
      billing_transparency: 3,
      wait_time: 3,
    },
    structured: {
      treatment_category: "Medical Management",
      treatment_speciality: "Neurology Department",
      treatment_procedure: "Neurology second opinion",
      days_admitted: 0,
      insurance_used: false,
    },
    verification_tier: "verified",
    weight: 1,
    is_anonymous: false,
    status: "published",
    helpful_count: 21,
    report_count: 0,
    visit_date: "2026-05-21",
    bill_amount: p(3_400),
    published_at: "2026-05-23",
    edited_at: null,
    reply: null,
  },
  {
    id: "01JB1009",
    business_id: "01J8SAHY",
    business_slug: "sahyadri-hospital-deccan",
    author: {
      id: "u_meera",
      display_name: "Meera J.",
      trust_level: 3,
      verified_review_count: 7,
    },
    rating: 2,
    title: "₹31,000 of the bill was 'miscellaneous'",
    body: "One line, no breakdown, no explanation until I refused to pay and asked for it in writing. It took two days to get an itemised copy. Everything else about the stay was ordinary and fine.",
    language: "en",
    aspect_ratings: {
      billing_transparency: 1,
      wait_time: 2,
      staff_behaviour: 3,
      cleanliness: 4,
      doctor_quality: 4,
    },
    structured: {
      treatment_category: "Surgical Treatment",
      treatment_speciality: "Urology",
      treatment_procedure: "PCNL-Percutaneous Nephrolithotomy",
      days_admitted: 2,
      insurance_used: true,
    },
    verification_tier: "verified",
    weight: 1,
    is_anonymous: false,
    status: "published",
    helpful_count: 58,
    report_count: 0,
    visit_date: "2026-07-02",
    bill_amount: p(94_700),
    published_at: "2026-07-05",
    edited_at: null,
    reply: {
      id: "rep_2",
      business_id: "01J8SAHY",
      author_display_name: "Sahyadri Hospital",
      created_at: "2026-07-08",
      body: "This is not the standard we hold ourselves to. The itemised breakdown should be available at the billing desk on request at any point during the stay, and we have re-briefed the team.",
    },
  },
  {
    id: "01JB1010",
    business_id: "01J8JEHA",
    business_slug: "jehangir-hospital-pune",
    author: null,
    rating: 4,
    title: "Paediatric ward handled a scared six-year-old well",
    body: "Nurses were genuinely good with my son, which mattered more than anything else that week. Bill was slightly over estimate but within reason.",
    language: "en",
    aspect_ratings: {
      doctor_quality: 5,
      cleanliness: 4,
      wait_time: 4,
      staff_behaviour: 4,
      billing_transparency: 3,
    },
    structured: {
      treatment_category: "Surgical Treatment",
      treatment_speciality: "General Surgery",
      treatment_procedure: "Lap Appendectomy",
      days_admitted: 2,
      insurance_used: true,
    },
    verification_tier: "verified",
    weight: 1,
    is_anonymous: true,
    status: "published",
    helpful_count: 33,
    report_count: 0,
    visit_date: "2026-06-17",
    bill_amount: p(38_200),
    published_at: "2026-06-19",
    edited_at: null,
    reply: null,
  },
  {
    id: "01JB1011",
    business_id: "01J8SHAH",
    business_slug: "dr-shah-skin-clinic-kothrud",
    author: {
      id: "u_farah",
      display_name: "Farah S.",
      trust_level: 4,
      verified_review_count: 14,
    },
    rating: 5,
    title: "Told me I did not need the expensive option",
    body: "Went in expecting to be sold a laser package. Dr. Shah said a ₹600 topical course would do it and to come back in six weeks if it did not. It did. Posting the ₹600 bill because that is the whole point of this site.",
    language: "en",
    aspect_ratings: {
      doctor_quality: 5,
      billing_transparency: 5,
      cleanliness: 5,
      staff_behaviour: 4,
      wait_time: 4,
    },
    structured: {
      treatment_category: "Clinical",
      treatment_speciality: "Skin and Cosmetic",
      treatment_procedure: "Skin care Treatment",
      insurance_used: false,
    },
    verification_tier: "verified",
    weight: 1,
    is_anonymous: false,
    status: "published",
    helpful_count: 205,
    report_count: 0,
    visit_date: "2026-05-09",
    bill_amount: p(600),
    published_at: "2026-05-10",
    edited_at: null,
    reply: null,
  },
  {
    id: "01JB1012",
    business_id: "01J8METR",
    business_slug: "metropolis-labs-shivajinagar",
    author: {
      id: "u_rohit",
      display_name: "Rohit A.",
      trust_level: 3,
      verified_review_count: 8,
    },
    rating: 4,
    title: "Full panel, report in eight hours",
    body: "Sample at 7:30am, PDF in my inbox by 3:40pm. The package price online and the price at the counter were ₹300 apart, which is the only reason this is not five stars.",
    language: "en",
    aspect_ratings: {
      turnaround: 5,
      accuracy: 4,
      cleanliness: 4,
      staff_behaviour: 4,
      billing_transparency: 3,
    },
    structured: {
      test_type: "Full body panel",
      report_hours: 8,
      home_collection: false,
    },
    verification_tier: "verified",
    weight: 1,
    is_anonymous: false,
    status: "published",
    helpful_count: 44,
    report_count: 0,
    visit_date: "2026-07-09",
    bill_amount: p(2_150),
    published_at: "2026-07-09",
    edited_at: null,
    reply: null,
  },
  {
    id: "01JB1013",
    business_id: "01J8SMIL",
    business_slug: "smilecare-dental-aundh",
    author: null,
    rating: 4,
    title: "Implant quote was ₹38,000, final bill ₹47,500",
    body: "The work itself was painless and the result is good. But a bone graft was added mid-treatment and the cost only came up at the end. Ask for the full plan in writing before the first sitting.",
    language: "en",
    aspect_ratings: {
      doctor_quality: 5,
      pain_management: 5,
      cleanliness: 4,
      wait_time: 4,
      billing_transparency: 2,
    },
    structured: {
      treatment_category: "Clinical",
      treatment_speciality: "Dental Treatment",
      treatment_procedure: "Dental Bridge and Implant",
      sittings: 4,
      quote_matched: false,
    },
    verification_tier: "verified",
    weight: 1,
    is_anonymous: true,
    status: "published",
    helpful_count: 91,
    report_count: 0,
    visit_date: "2026-04-02",
    bill_amount: p(47_500),
    published_at: "2026-04-28",
    edited_at: null,
    reply: null,
  },
];

/* -------------------------------------------------------------------------- */
/* Vault — GET /me/receipts                                                    */
/* -------------------------------------------------------------------------- */

export const VAULT_DTOS: VaultReceiptDto[] = [
  {
    id: "01J9RC01",
    business: {
      id: "01J8RUBY",
      slug: "ruby-hall-clinic-pune",
      name: "Ruby Hall Clinic",
    },
    total_amount: p(42_300),
    txn_date: "2026-03-14",
    status: "verified",
    consumed_by_review_id: "01JB1001",
    purge_after: "2026-06-12",
  },
  {
    id: "01J9RC02",
    business: {
      id: "01J8SHAH",
      slug: "dr-shah-skin-clinic-kothrud",
      name: "Dr. Shah Skin & Laser Clinic",
    },
    total_amount: p(600),
    txn_date: "2026-05-09",
    status: "verified",
    consumed_by_review_id: "01JB1011",
    purge_after: "2026-08-07",
  },
  {
    id: "01J9RC03",
    business: {
      id: "01J8METR",
      slug: "metropolis-labs-shivajinagar",
      name: "Metropolis Diagnostics",
    },
    total_amount: p(1_890),
    txn_date: "2026-07-21",
    status: "verified",
    consumed_by_review_id: null,
    purge_after: "2026-10-19",
  },
];

/** Platform counters behind the proof-of-life strip — see api-additions.md §1. */
export const PLATFORM_STATS = {
  bills_verified: 4_18_207,
  reviews_published: 1_02_884,
  bills_verified_this_week: { city: "Pune", count: 1_204 },
};
