import type { TreatmentCategoryDto } from "./types";

/**
 * Treatment taxonomy in **wire shape** — served by the mock transport at
 * `GET /treatments`, the same API the place names come from. Three levels:
 * category → speciality → procedure, which is exactly how the write flow asks
 * for it.
 *
 * Kept verbatim as the backend supplies it, spelling and all — normalising it
 * here would mean the labels stop matching the ones the backend stores, and
 * this file disappears the moment `NEXT_PUBLIC_API_BASE_URL` is set.
 */
export const TREATMENT_DTOS: TreatmentCategoryDto[] = [
  {
    categoryName: "Medical Management",
    specialities: [
      {
        specialityName: "Infectious Disease",
        procedureName: [
          "Viral fever Management",
          "Fever Management",
          "Dengue Fever Management",
          "Typhoid Fever Management",
          "Malaria Fever Management",
          "Rickettsial Fever Management",
          "Others",
        ],
      },
      {
        specialityName: "Respiratory Tract Infections",
        procedureName: [
          "Upper Respiratory Tract Infection",
          "Lower Respiratory Tract Infection",
          "Bronchitis Managment",
          "Pharyngitis Management",
          "Covid Management",
          "H1N1 Flu management",
          "Influenza Management",
          "Respiratory Failure Management",
          "Others",
        ],
      },
      {
        specialityName: "ENT Disease Management",
        procedureName: [
          "Ear Infection Management",
          "Sinusitis Management",
          "Tonsillitis Management",
          "Throat Infection",
          "Thyroid /Parathyroid Disorder",
          "Others",
        ],
      },
      {
        specialityName: "Pulmonology Disease Management",
        procedureName: [
          "Chest Infection Management",
          "Pneumonia Management",
          "Lung Infection Management",
          "Pleaural Effusion Management",
          "Others",
        ],
      },
      {
        specialityName: "Opthalmology Disease Management",
        procedureName: [
          "Eye Infection Management",
          "Conjunctivitis Management",
          "Others",
        ],
      },
      {
        specialityName: "General Medicine Department",
        procedureName: [
          "Septic Shock Management",
          "Sepsis Management",
          "Joint Pain Management",
          "Osteoarthritis Management",
          "Others",
        ],
      },
      {
        specialityName: "Cardiovascular Department",
        procedureName: [
          "Arrythmia Management",
          "Hypertensive Emergency Management",
          "Diabetic Management",
          "Heart Attack Medical Management",
          "Myocardial Infarction Management",
          "Others",
        ],
      },
      {
        specialityName: "Gastro-Enterology Department",
        procedureName: [
          "Abdominal Pain Management",
          "Liver Disease Management",
          "Hepatitis Management",
          "Jaundice management",
          "Spleen disease",
          "Cholecystitis Management",
          "Gastric Pain Management",
          "Ulcer Management",
          "Pancreatitis Management",
          "Intestinal Obstruction Management",
          "Gall bladder Stone Management",
          "Others",
        ],
      },
      {
        specialityName: "Neurology Department",
        procedureName: [
          "Stroke Management",
          "Meningitis Management",
          "Head Injury Management",
          "Neuro ICU Management",
          "Others",
        ],
      },
      {
        specialityName: "Nephrology Department",
        procedureName: [
          "Urinary Tract Infection Management",
          "Kidney Stone Management",
          "Bladder Obstruction management",
          "Kidney Infection Management",
          "Glomerulonephritis Management",
          "Acute Kidney Injury",
          "Acute Nephrotic Syndrome",
          "Chronic Kidney Disease stage 5",
          "Pyelonephritis Management",
          "Others",
        ],
      },
      {
        specialityName: "Orthopedic Department",
        procedureName: [
          "Blunt Trauma Management",
          "Lumbar spondylosis Management",
          "Cervical Spondylosis Management",
          "Trauma Medical management",
          "Others",
        ],
      },
      {
        specialityName: "Pediatric Department",
        procedureName: [
          "Neonatal Jaundice Management",
          "TTN-Transient Tachypnoea Management",
          "Physiological Jaundice Management",
          "New Born ICU Management",
          "Others",
        ],
      },
      {
        specialityName: "Skin Disease Management",
        procedureName: [
          "Eczema",
          "Psoriasis",
          "Skin Rash",
          "Hair Loss Management",
          "Skin Infection Management",
          "Others",
        ],
      },
      {
        specialityName: "Endocrinology Department",
        procedureName: [
          "Hormonal Dysfunction Management",
          "Hyperthyroidism",
          "Hypothyroidism",
          "Growth Hormone disorder",
          "Others",
        ],
      },
      {
        specialityName: "Medical Management Ward",
        procedureName: ["IV Antibiotics", "IV Fluids", "Others"],
      },
      {
        specialityName: "Medical Management ICU/CCU",
        procedureName: [
          "With Bipap Support",
          "With Ventilator Support",
          "Oxygen Support Only",
          "ICU Care Only",
          "Others",
        ],
      },
    ],
  },
  {
    categoryName: "Surgical Treatment",
    specialities: [
      {
        specialityName: "Cardiology",
        procedureName: [
          "Angiography",
          "Angioplasty",
          "Angiography with Angioplasty",
          "CABG",
          "Valve replacement",
          "Temporary Pacemaker Implantation",
          "Permanant Pacemaker Implantation",
          "DVR-Double Valve Replacement",
          "EPS with RFA",
          "Others",
        ],
      },
      {
        specialityName: "ENT",
        procedureName: [
          "Tonsillectomy",
          "Adenoidectomy",
          "Adenotonsillectomy",
          "Tympanoplasty",
          "Mastoidectomy",
          "Mastoidectomy with Tympanoplasty",
          "FESS with Septoplasty",
          "Turbinectomy or Polypectomy",
          "Chonchoplasty",
          "Cortical Mastoidectomy with Myringoplasty",
          "Peritonsillar Abscess Drainage",
          "Micro laryngeal Surgeries for Cysts and Polyps",
          "Myringotomy with Grommet Insertion",
          "Others",
        ],
      },
      {
        specialityName: "General Surgery",
        procedureName: [
          "Hemorrhoidectomy",
          "Fissurectomy",
          "Hemorrhoidectomy with Fissurectomy",
          "High End Fistulectomy",
          "Low End Fistulectomy",
          "Lap Appendectomy",
          "Open Appendectomy",
          "Open Cholecystectomy",
          "Lap Cholecystectomy",
          "Excision of Pilonidal Sinus",
          "Simple Mastectomy",
          "Radical Mastectomy",
          "Modified Radical Mastectomy",
          "Thyroidectomy (Total/Subtotal/Partial)",
          "Isthmectomy",
          "Inguinal Hernioplasty",
          "Femoral Hernioplasty",
          "Umbilical Hernioplasty",
          "Incisional Hernioplasty",
          "Circumcision",
          "Perianal Abscess Drainage",
          "Breast Lumpectomy",
          "AV Fistula",
          "Hydrocele",
          "Hemicolectomy",
          "Resection and Anastomosis of intestine",
          "ERCP Stenting",
          "CBD stone removal",
          "Others",
        ],
      },
      {
        specialityName: "Gynecology",
        procedureName: [
          "Normal Delivery",
          "Instrumental Delivery",
          "LSCS-Caesarean section",
          "Vaginal Hysterectomy",
          "Abdominal Hysterectomy",
          "Total Laparoscopic Hysterectomy",
          "Hysterectomy with Pelvic Floor repair",
          "Open Ovarian Cystectomy",
          "Lap Ovarian Cystectomy",
          "MTP-D&C",
          "Open Myomectomy",
          "Lap Myomectomy",
          "Others",
        ],
      },
      {
        specialityName: "Ophthalmology",
        procedureName: [
          "Cataract -Phaco /MICS",
          "Vitrectomy",
          "Pars Plana Vitrectomy",
          "Vitrectomy with Gas Tamponade",
          "Vitrectomy with Membrane Peeling with Endo laser",
          "Suture less Vitrectomy",
          "Trabeculectomy",
          "Trabeculectomy with MMC",
          "Trabeculectomy with Ologen",
          "Retinal Detachment Surgery-Scleral buckling",
          "C3R-Corneal Collagen Cross linking with Riboflavin",
          "Others",
        ],
      },
      {
        specialityName: "Orthopedics",
        procedureName: [
          "Total Knee Replacement",
          "Total Hip Replacement",
          "Fracture Neck Femur",
          "Hemiarthroplasty",
          "Fracture Shaft Femur",
          "Tibia Fracture Unicondyler-ORIF",
          "Tibia Fracture Bicondyler-ORIF",
          "Ankle Fracture-ORIF with TBW",
          "Arthrodesis-Wrist/Ankle/Subtalar",
          "Hand or Foot Fracture with Plates or Screws",
          "Calcaneal Fracture with plates",
          "Open Reduction and Internal Fixation-Humerus",
          "Open Reduction and Internal Fixation-Shoulder",
          "Open Reduction and Internal Fixation-Both Bones Forearm",
          "Open Reduction and Internal Fixation-Single Bone Forearm",
          "Scaphoid fixation",
          "Arthroscopic Debridement and Synovectomy",
          "Shoulder-Arthroscopy Bankart repair",
          "Shoulder-Arthroscopy/Open Sub Acromial Decompression",
          "ACL reconstruction/repair",
          "MCL Reconstruction/Repair",
          "ACL/PCL Reconstruction/Repair",
          "Carpel Tunnel Release",
          "Closed Reduction of Fractures",
          "Implant Removal-Small Bones",
          "Implant Removal-Large Bones",
          "Bone Grafting of Non Union -Small bones",
          "Bone Grafting of Non Union -Large bones",
          "Acetabular Fracture Fixation",
          "Pelvis fracture -Fixation",
          "Reduction-Dislocation under GA",
          "Amputation of Single Digit",
          "Amputation of Multiple Digit",
          "Amputation Below Knee/Elbow",
          "Amputation Above Knee/Elbow",
          "Small Wound Debridement",
          "Large Wound Debridement",
          "Tendon Repair",
          "Others",
        ],
      },
      {
        specialityName: "Spinal Surgery",
        procedureName: [
          "Laminectomy",
          "Discectomy",
          "Stabilization of Cervical Spine",
          "Thoraco Lumbar Spine Fixation",
          "Thoraco-Lumbar Anterior Interbody Fixation",
          "Implant Removal of Spine",
          "Others",
        ],
      },
      {
        specialityName: "Urology",
        procedureName: [
          "PCNL-Percutaneous Nephrolithotomy",
          "Open TURP",
          "Laser TURP",
          "Holmium laser TURP",
          "Meatotomy",
          "Dialysis",
          "Renal Transplant Surgery",
          "Cystoscopy Diagnostic",
          "Cystoscopy Therapeutic",
          "Cystoscopy with URS with DJ stenting",
          "URS Therapeutic",
          "DJ stent removal",
          "Lap Nephrectomy",
          "Open Nephrectomy",
          "Nephrolithotomy",
          "Orchidectomy",
          "ESWL-Extra Corporeal Shock Wave Lithotripsy",
          "Others",
        ],
      },
      {
        specialityName: "Neurology",
        procedureName: [
          "VP Shunting",
          "Craniotomy with Evacuation of Hematoma",
          "Cranioplasty",
          "Decompressive Craniectomy",
          "Burr Hole Surgery",
          "Others",
        ],
      },
      {
        specialityName: "Vascular Surgery",
        procedureName: [
          "Varicose Vein Surgical",
          "Varicose vein Laser",
          "Varicose Vein Radio Frequnecy Ablation",
          "Others",
        ],
      },
      {
        specialityName: "Plastic Surgery",
        procedureName: [
          "Plastic Surgery",
          "Contracture release",
          "Wound debridement with Flap Repair",
          "Others",
        ],
      },
      {
        specialityName: "Oncology",
        procedureName: [
          "Oncosurgery",
          "Radiotherapy",
          "Chemotherapy",
          "Others",
        ],
      },
      {
        specialityName: "Pediatric Surgery",
        procedureName: [
          "Pediatric Cardiothoracic Surgery",
          "Pediatric Orthopedic Surgery",
          "Pediatric Oncology",
          "Pediatric Urology",
          "Pediatric Neurology",
          "Others",
        ],
      },
      {
        specialityName: "Organ Transplantation",
        procedureName: [
          "Kidney Transplantation",
          "Liver Transplantation",
          "Heart Transplantation",
          "Others",
        ],
      },
      {
        specialityName: "Pulmonology",
        procedureName: ["Lung Related Treatment", "Others"],
      },
      {
        specialityName: "Cosmetology",
        procedureName: [
          "Skin care Treatment",
          "Hair Care Treatment",
          "Obesity Treatment",
          "Others",
        ],
      },
      {
        specialityName: "Emergency Medicine",
        procedureName: [
          "Casulaty Management for RTA",
          "Casulaty Management for Medical Illness",
          "Others",
        ],
      },
      {
        specialityName: "Preventive Medicine",
        procedureName: ["Preventive Medical Care", "Others"],
      },
      {
        specialityName: "Interventional Radiology",
        procedureName: ["Interventional Radiology", "Others"],
      },
    ],
  },
  {
    categoryName: "Clinical",
    specialities: [
      {
        specialityName: "Skin and Cosmetic",
        procedureName: ["Skin care Treatment", "Hair Transplant", "Others"],
      },
      {
        specialityName: "Dental Treatment",
        procedureName: [
          "Root Canal",
          "Dental alignment with Braces",
          "Tooth Extraction",
          "Cavity Fillings",
          "Fluoride Treatments",
          "Dental Bonding",
          "Gum Surgery",
          "Dental Crowns",
          "Dental Restoration",
          "Dental Bridge and Implant",
          "Tooth Whitening",
          "Others",
        ],
      },
      {
        specialityName: "Infertility Treatment",
        procedureName: [
          "IUI-Intra Uterine Insemination",
          "IVF-In Vitro Fertilization",
          "Others",
        ],
      },
      {
        specialityName: "Asthetic",
        procedureName: ["Weightloss treatment", "Liposuction", "Others"],
      },
      {
        specialityName: "Eye Treatment",
        procedureName: [
          "Lasik Laser",
          "SMILE Lasik Treatment",
          "Contact Lens Treatment",
          "Phaco with Intra Ocular Lens",
          "Cataract Surgery",
          "MICS Cataract",
          "Others",
        ],
      },
    ],
  },
];
